In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
print(os.getcwd())
df = pd.read_csv('./Data/Pokemon.csv')

/Users/SHEN/Desktop/Pokemon

In [3]:
df.head(n=10)
df.tail(n=10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [4]:
legendary = df[df['Legendary']==True]
print(len(legendary))
print(legendary)

65
       #                      Name    Type 1    Type 2  Total   HP  Attack  \
156  144                  Articuno       Ice    Flying    580   90      85
157  145                    Zapdos  Electric    Flying    580   90      90
158  146                   Moltres      Fire    Flying    580   90     100
162  150                    Mewtwo   Psychic       NaN    680  106     110
163  150       MewtwoMega Mewtwo X   Psychic  Fighting    780  106     190
164  150       MewtwoMega Mewtwo Y   Psychic       NaN    780  106     150
262  243                    Raikou  Electric       NaN    580   90      85
263  244                     Entei      Fire       NaN    580  115     115
264  245                   Suicune     Water       NaN    580  100      75
269  249                     Lugia   Psychic    Flying    680  106      90
270  250                     Ho-oh      Fire    Flying    680  106     130
414  377                  Regirock      Rock       NaN    580   80     100
415  378                    Regice       Ice       NaN    580   80      50
416  379                 Registeel     Steel       NaN    580   80      75
417  380                    Latias    Dragon   Psychic    600   80      80
418  380         LatiasMega Latias    Dragon   Psychic    700   80     100
419  381                    Latios    Dragon   Psychic    600   80      90
420  381         LatiosMega Latios    Dragon   Psychic    700   80     130
421  382                    Kyogre     Water       NaN    670  100     100
422  382       KyogrePrimal Kyogre     Water       NaN    770  100     150
423  383                   Groudon    Ground       NaN    670  100     150
424  383     GroudonPrimal Groudon    Ground      Fire    770  100     180
425  384                  Rayquaza    Dragon    Flying    680  105     150
426  384     RayquazaMega Rayquaza    Dragon    Flying    780  105     180
427  385                   Jirachi     Steel   Psychic    600  100     100
428  386        DeoxysNormal Forme   Psychic       NaN    600   50     150
429  386        DeoxysAttack Forme   Psychic       NaN    600   50     180
430  386       DeoxysDefense Forme   Psychic       NaN    600   50      70
431  386         DeoxysSpeed Forme   Psychic       NaN    600   50      95
537  480                      Uxie   Psychic       NaN    580   75      75
..   ...                       ...       ...       ...    ...  ...     ...
543  486                 Regigigas    Normal       NaN    670  110     160
544  487     GiratinaAltered Forme     Ghost    Dragon    680  150     100
545  487      GiratinaOrigin Forme     Ghost    Dragon    680  150     120
549  491                   Darkrai      Dark       NaN    600   70      90
550  492         ShayminLand Forme     Grass       NaN    600  100     100
551  492          ShayminSky Forme     Grass    Flying    600  100     103
552  493                    Arceus    Normal       NaN    720  120     120
553  494                   Victini   Psychic      Fire    600  100     100
699  638                  Cobalion     Steel  Fighting    580   91      90
700  639                 Terrakion      Rock  Fighting    580   91     129
701  640                  Virizion     Grass  Fighting    580   91      90
702  641   TornadusIncarnate Forme    Flying       NaN    580   79     115
703  641     TornadusTherian Forme    Flying       NaN    580   79     100
704  642  ThundurusIncarnate Forme  Electric    Flying    580   79     115
705  642    ThundurusTherian Forme  Electric    Flying    580   79     105
706  643                  Reshiram    Dragon      Fire    680  100     120
707  644                    Zekrom    Dragon  Electric    680  100     150
708  645   LandorusIncarnate Forme    Ground    Flying    600   89     125
709  645     LandorusTherian Forme    Ground    Flying    600   89     145
710  646                    Kyurem    Dragon       Ice    660  125     130
711  646        KyuremBlack Kyurem    Dragon       Ice    700  125     170
712  646        KyuremWhite Kyurem    Dragon       Ice    700  125     120
792  716                   Xerneas     Fairy       NaN    680  126     131
793  717                   Yveltal      Dark    Flying    680  126     131
794  718          Zygarde50% Forme    Dragon    Ground    600  108     100
795  719                   Diancie      Rock     Fairy    600   50     100
796  719       DiancieMega Diancie      Rock     Fairy    700   50     160
797  720       HoopaHoopa Confined   Psychic     Ghost    600   80     110
798  720        HoopaHoopa Unbound   Psychic      Dark    680   80     160
799  721                 Volcanion      Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
156      100       95      125     85           1       True
157       85      125       90    100           1       True
158       90      125       85     90           1       True
162       90      154       90    130           1       True
163      100      154      100    130           1       True
164       70      194      120    140           1       True
262       75      115      100    115           2       True
263       85       90       75    100           2       True
264      115       90      115     85           2       True
269      130       90      154    110           2       True
270       90      110      154     90           2       True
414      200       50      100     50           3       True
415      100      100      200     50           3       True
416      150       75      150     50           3       True
417       90      110      130    110           3       True
418      120      140      150    110           3       True
419       80      130      110    110           3       True
420      100      160      120    110           3       True
421       90      150      140     90           3       True
422       90      180      160     90           3       True
423      140      100       90     90           3       True
424      160      150       90     90           3       True
425       90      150       90     95           3       True
426      100      180      100    115           3       True
427      100      100      100    100           3       True
428       50      150       50    150           3       True
429       20      180       20    150           3       True
430      160       70      160     90           3       True
431       90       95       90    180           3       True
537      130       75      130     95           4       True
..       ...      ...      ...    ...         ...        ...
543      110       80      110    100           4       True
544      120      100      120     90           4       True
545      100      120      100     90           4       True
549       90      135       90    125           4       True
550      100      100      100    100           4       True
551       75      120       75    127           4       True
552      120      120      120    120           4       True
553      100      100      100    100           5       True
699      129       90       72    108           5       True
700       90       72       90    108           5       True
701       72       90      129    108           5       True
702       70      125       80    111           5       True
703       80      110       90    121           5       True
704       70      125       80    111           5       True
705       70      145       80    101           5       True
706      100      150      120     90           5       True
707      120      120      100     90           5       True
708       90      115       80    101           5       True
709       90      105       80     91           5       True
710       90      130       90     95           5       True
711      100      120       90     95           5       True
712       90      170      100     95           5       True
792       95      131       98     99           6       True
793       95      131       98     99           6       True
794      121       81       95     95           6       True
795      150      100      150     50           6       True
796      110      160      110    110           6       True
797       60      150      130     70           6       True
798       60      170      130     80           6       True
799      120      130       90     70           6       True

[65 rows x 13 columns]

In [5]:
# Change and set the index to 'Name'
df = df.set_index('Name')
df.head(n=10)

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
Charmeleon,5,Fire,NaN,405,58,64,58,80,65,80,1,False
Charizard,6,Fire,Flying,534,78,84,78,109,85,100,1,False
CharizardMega Charizard X,6,Fire,Dragon,634,78,130,111,130,85,100,1,False
CharizardMega Charizard Y,6,Fire,Flying,634,78,104,78,159,115,100,1,False
Squirtle,7,Water,NaN,314,44,48,65,50,64,43,1,False

In [6]:
# Remove repeated text in Mega pokemon names
df.index = df.index.str.replace('.*(?=Mega)', '')
df.head(n=10)

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
Mega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
Charmeleon,5,Fire,NaN,405,58,64,58,80,65,80,1,False
Charizard,6,Fire,Flying,534,78,84,78,109,85,100,1,False
Mega Charizard X,6,Fire,Dragon,634,78,130,111,130,85,100,1,False
Mega Charizard Y,6,Fire,Flying,634,78,104,78,159,115,100,1,False
Squirtle,7,Water,NaN,314,44,48,65,50,64,43,1,False

In [7]:
# Drop col with axis = 1; axis = 0 is for rows
df = df.drop(['#'], axis = 1)
#fill NaN values in Type2 with corresponding values of Type
df['Type 2'].fillna(df['Type 1'], inplace=True)

print('The Cols of the data are: \n', df.columns)
print('The shape of the data is: \n', df.shape)

The Cols of the data are:
 Index(['Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
The shape of the data is:
 (800, 11)

In [10]:
print(df.loc['Bulbasaur'])
print(df.iloc[0])

Type 1         Grass
Type 2        Poison
Total            318
HP                45
Attack            49
Defense           49
Sp. Atk           65
Sp. Def           65
Speed             45
Generation         1
Legendary      False
Name: Bulbasaur, dtype: object
Type 1         Grass
Type 2        Poison
Total            318
HP                45
Attack            49
Defense           49
Sp. Atk           65
Sp. Def           65
Speed             45
Generation         1
Legendary      False
Name: Bulbasaur, dtype: object

/Users/SHEN/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated